In [1]:
import os
os.chdir("C:\\Users\\zharif\\Documents\\Dataset TA")  # Move to climate-research-workbench root
print(f"CWD: {os.getcwd()}")

CWD: C:\Users\zharif\Documents\Dataset TA

In [2]:
import xarray as xr

In [3]:
ds_truth = xr.open_zarr("data/era5_indonesia_2018-2022.zarr")
ds_forecast = xr.open_zarr("data/ifs_lowres_indonesia_2018-2022.zarr")

C:\Users\zharif\AppData\Local\Temp\ipykernel_24076\3191457552.py:2: FutureWarning: In a future version, xarray will not decode timedelta values based on the presence of a timedelta-like units attribute by default. Instead it will rely on the presence of a timedelta64 dtype attribute, which is now xarray's default way of encoding timedelta64 values. To continue decoding timedeltas based on the presence of a timedelta-like units attribute, users will need to explicitly opt-in by passing True or CFTimedeltaCoder(decode_via_units=True) to decode_timedelta. To silence this warning, set decode_timedelta to True, False, or a 'CFTimedeltaCoder' instance.
  ds_forecast = xr.open_zarr("data/ifs_lowres_indonesia_2018-2022.zarr")

In [4]:
ds_truth

<xarray.Dataset> Size: 4GB
Dimensions:                   (time: 7304, latitude: 181, longitude: 201)
Coordinates:
  * latitude                  (latitude) float32 724B 30.0 29.75 ... -15.0
  * longitude                 (longitude) float32 804B 90.0 90.25 ... 140.0
  * time                      (time) datetime64[ns] 58kB 2018-01-01 ... 2022-...
Data variables:
    10m_u_component_of_wind   (time, latitude, longitude) float32 1GB dask.array<chunksize=(1, 181, 201), meta=np.ndarray>
    10m_v_component_of_wind   (time, latitude, longitude) float32 1GB dask.array<chunksize=(1, 181, 201), meta=np.ndarray>
    2m_temperature            (time, latitude, longitude) float32 1GB dask.array<chunksize=(1, 181, 201), meta=np.ndarray>
    total_precipitation_24hr  (time, latitude, longitude) float32 1GB dask.array<chunksize=(1, 181, 201), meta=np.ndarray>

In [5]:
ds_truth.to_dataframe()

                                        10m_u_component_of_wind  \
time                latitude longitude
2018-01-01 00:00:00  30.0    90.00                     0.737060
                             90.25                     0.848293
                             90.50                     0.751659
                             90.75                     1.359269
                             91.00                     1.275149
...                                                         ...
2022-12-31 18:00:00 -15.0    139.00                    9.118832
                             139.25                    9.269753
                             139.50                    9.616480
                             139.75                    9.967110
                             140.00                    9.986626

                                        10m_v_component_of_wind  \
time                latitude longitude
2018-01-01 00:00:00  30.0    90.00                     2.006315
                             90.25                     1.735711
                             90.50                     1.611551
                             90.75                     1.079256
                             91.00                    -0.203726
...                                                         ...
2022-12-31 18:00:00 -15.0    139.00                   -4.179657
                             139.25                   -4.423280
                             139.50                   -4.873521
                             139.75                   -5.411652
                             140.00                   -6.373039

                                        2m_temperature  \
time                latitude longitude
2018-01-01 00:00:00  30.0    90.00          257.477081
                             90.25          259.331238
                             90.50          260.596741
                             90.75          261.198395
                             91.00          262.092194
...                                                ...
2022-12-31 18:00:00 -15.0    139.00         301.053131
                             139.25         301.656464
                             139.50         302.035309
                             139.75         302.041534
                             140.00         302.055573

                                        total_precipitation_24hr
time                latitude longitude
2018-01-01 00:00:00  30.0    90.00                      0.000720
                             90.25                      0.000388
                             90.50                      0.000194
                             90.75                      0.000277
                             91.00                      0.000854
...                                                          ...
2022-12-31 18:00:00 -15.0    139.00                     0.069636
                             139.25                     0.070952
                             139.50                     0.066852
                             139.75                     0.061051
                             140.00                     0.057606

[265726824 rows x 4 columns]

In [6]:
ds_forecast.to_dataframe()

                                                             10m_u_component_of_wind  \
time                prediction_timedelta longitude latitude
2018-01-01 00:00:00 0 days               90.0      -13.5                   -7.348840
                                                   -12.0                   -6.890699
                                                   -10.5                   -6.357089
                                                   -9.0                    -3.722364
                                                   -7.5                    -0.676742
...                                                                              ...
2022-12-31 12:00:00 15 days              150.0      24.0                   -3.501121
                                                    25.5                   -1.805219
                                                    27.0                   -0.056934
                                                    28.5                    2.053200
                                                    30.0                    4.686364

                                                             10m_v_component_of_wind  \
time                prediction_timedelta longitude latitude
2018-01-01 00:00:00 0 days               90.0      -13.5                    4.691245
                                                   -12.0                    4.924768
                                                   -10.5                    5.328537
                                                   -9.0                     4.174468
                                                   -7.5                     3.523671
...                                                                              ...
2022-12-31 12:00:00 15 days              150.0      24.0                   -2.219328
                                                    25.5                   -2.275626
                                                    27.0                   -2.107670
                                                    28.5                   -1.530470
                                                    30.0                   -0.693202

                                                             2m_temperature  \
time                prediction_timedelta longitude latitude
2018-01-01 00:00:00 0 days               90.0      -13.5         299.417358
                                                   -12.0         299.876007
                                                   -10.5         300.020752
                                                   -9.0          299.114868
                                                   -7.5          299.891418
...                                                                     ...
2022-12-31 12:00:00 15 days              150.0      24.0         295.012390
                                                    25.5         293.841888
                                                    27.0         292.442505
                                                    28.5         291.086884
                                                    30.0         289.909363

                                                             total_precipitation_24hr
time                prediction_timedelta longitude latitude
2018-01-01 00:00:00 0 days               90.0      -13.5                          NaN
                                                   -12.0                          NaN
                                                   -10.5                          NaN
                                                   -9.0                           NaN
                                                   -7.5                           NaN
...                                                                               ...
2022-12-31 12:00:00 15 days              150.0      24.0                     0.004437
                                                    25.5                     0.004026
                                                    27.0                     0.002949
                                                    28.5                     0.002151
                                                    30.0                     0.001688

[274009560 rows x 4 columns]

In [13]:
ds_forecast['2m_temperature'].sel(time='2018-01-01', prediction_timedelta='0 days', latitude=0, longitude=90).to_dataframe()

                     latitude  longitude prediction_timedelta  2m_temperature
time
2018-01-01 00:00:00       0.0       90.0               0 days      300.973022
2018-01-01 12:00:00       0.0       90.0               0 days      299.521271

In [14]:
ds_truth['2m_temperature'].sel(time='2018-01-01', latitude=0, longitude=90).to_dataframe()

                     latitude  longitude  2m_temperature
time
2018-01-01 00:00:00       0.0       90.0      299.708588
2018-01-01 06:00:00       0.0       90.0      300.777374
2018-01-01 12:00:00       0.0       90.0      299.430908
2018-01-01 18:00:00       0.0       90.0      299.130066